export default {
  LoginToTicketex: "Login to Ticketex",
  WelcomeAtLogin: "Welcome to Ticketex, login to our app",
  MobileNo: "Mobile number",
  Login: "Login",
  Home: "Home",
  SellTicket: "Sell Ticket",
  AddTicket: "AddTicket",
  PurchasedTicket: "Purchased Ticket",
  Account: "Account",
  MyAccount: "My Account",
  Balance: "Balance",
  BankAccount: "Bank Account",
  CreditCard: "Credit Card",
  ContactUs: "Contact Us",
  FAQs: "FAQs",
  SignOut: "Sign Out",
  AddNewCreditCard: "Add New Credit card",
  AddBankAccount: "Add Bank Account",
  YourSellingBalanceIs: "Your Selling Balance is",
  BalancePageBigText:
    "You can use this balance to buy other ticket or you can request transfer to your bank account",
  WithdrawBalance: "Withdraw Balance",
  BankName: "Bank Name",
  BeneficiaryName: "Beneficiary Name",
  IBAN: "IBAN",
  AddNewBank: "Add New Bank",
  CardNumber: "Card Number",
  CardHolderName: "Card Holder Name",
  Expire: "Expire",
  CVV: "CVV",
  PhoneNumber: "Phone Number",
  MessageHere: "Message Here",
  Send: "Send",
  TicketDetails: "Ticket Details",
  OpenOnGoogleMaps: "Open on google maps",
  OrYouCanScanQRCode: "Or you can scan QR code",
  MyListing: "My Listing",
  Sold: "Sold",
  Expired: "Expired",
  Listed: "Listed",
  BuyNow: "Buy Now",
  OriginalSellingPrices: "Original Selling Prices",
  Available: "Available",
  TicketsSold: "Tickets Sold",
  PriceIncludesFees: "Price includes fees",
  AvailableTickets: "Available Tickets",
  ShowMore: "Show More",
  Search: "Search",
  MyTickets: "My Tickets",
  OTP_Number: "OTP Number",
  AddTicket: "Add Ticket",
  Next: "Next",
  SelectCategory: "Select category",
  SelectCity: "Select city",

  TicketsSold: "Tickets Sold",
  OneTicketFor: "1 Ticket for",
  Loading: "Loading",
  EnterYourBankIban: "Enter your bank iban.",
  EnterYourBankBeneficiaryName: "Enter your bank beneficiary name.",
  EnterYourBankName: "Enter your bank name.",

  SelectEventType: "Select Event Type:",
  SelectClassType: "Select Class Type:",
  Quantity: "Quantity:",
  PricePerTicket: "Price Per Ticket(SAR)",
  Note: "Based on ticket class the price should not exceed 240 SAR",
  TicketName: "Ticket Name",
  TicketDescription: "Ticket Description",
  SelectQrOption: "Select Scan or upload the ticket QR Code",
  UploadQRCode: "Upload QR Code",
  ScanQRCode: "Scan QR Code",
  Next: "Next",
  Price: "Price",
  TypeToSearch: "Type here to search...",
  EnterPrice: "Enter ticket price.",
  EnterName: "Enter ticket name.",

  EnterPhoneNo: "Enter your phone number.",
  EnterMessage: "Enter your message.",

  AccesCameraDenied: "Acess to camera denied",

  Clear: "clear",

  PleaseSelectImage: "Please select a image.",
  AreYouSure: "Are you sure you want to submit!",
  Ok: "Ok",
  RequestingForCameraPermissions: "Requesting For Camera Permission",
  NoAccessToCamera: "No access to camera",
  ScannedData: "Scanned Data: ",
  Submit: "Submit",
  Scan: "Scan",
  Upload: "Upload",

  SoldTickets: "Sold Tickets",
  SomethingWentWrong: "Something went wrong!",
};
