export default {
  LoginToTicketex: "Login to Ticketex",
  WelcomeAtLogin: "Welcome to Ticketex, login to our app",
  MobileNo: "Mobile number",
  Login: "Login",
  Home: "Home",
  SellTicket: "Sell Ticket",
  AddTicket: "AddTicket",
  PurchasedTicket: "Purchased Ticket",
  Account: "Account",
  MyAccount: "My Account",
  Balance: "Balance",
  BankAccount: "Bank Account",
  CreditCard: "Credit Card",
  ContactUs: "Contact Us",
  FAQs: "FAQs",
  SignOut: "Sign Out",
  AddNewCreditCard: "Add New Credit card",
  AddBankAccount: "Add Bank Account",
  YourSellingBalanceIs: "Your Selling Balance is",
  BalancePageBigText:
    "You can use this balance to buy other ticket or you can request transfer to your bank account",
  WithdrawBalance: "Withdraw Balance",
  BankName: "Bank Name",
  BeneficiaryName: "Beneficiary Name",
  IBAN: "IBAN",
  AddNewBank: "Add New Bank",
  CardNumber: "Card Number",
  CardHolderName: "Card Holder Name",
  Expire: "Expire",
  CVV: "CVV",
  PhoneNumber: "Phone Number",
  MessageHere: "Message Here",
  Send: "Send",
  TicketDetails: "Ticket Details",
  OpenOnGoogleMaps: "Open on google maps",
  OrYouCanScanQRCode: "Or you can scan QR code",
  Sold: "Sold",
  Expired: "Expired",
  Listed: "Listed",
  BuyNow: "Buy Now",
  OriginalSellingPrices: "Original Selling Prices",
  Available: "Available",
  TicketsSold: "Tickets Sold",
  PriceIncludesFees: "Price includes fees",
  AvailableTickets: "Available Tickets",
  ShowMore: "Show More",
  Search: "Search",
  OTP_Number: "OTP Number",
  AddTicket: "Add Ticket",
  Next: "Next",
  SelectCategory: "Select category",
  SelectCity: "Select city",
  TicketsSold: "Tickets Sold",
  OneTicketFor: "1 Ticket for",
  Loading: "Loading",
  EnterYourBankIban: "Enter your bank iban.",
  EnterYourBankBeneficiaryName: "Enter your bank beneficiary name.",
  EnterYourBankName: "Enter your bank name.",
  SelectEventType: "Select Event Type",
  SelectClassType: "Select Class Type",
  Quantity: "Quantity",
  PricePerTicket: "Price Per Ticket",
  Note: "Based on ticket class the price should not exceed 240 SAR",
  TicketName: "Ticket Name",
  TicketDescription: "Ticket Description",
  Next: "Next",
  Price: "Price",
  TypeToSearch: "Type here to search...",
  EnterPrice: "Enter ticket price.",
  EnterName: "Enter ticket name.",
  EnterPhoneNo: "Enter your phone number.",
  EnterMessage: "Enter your message.",
  Clear: "clear",
  AreYouSure: "Are you sure you want to submit!",
  Ok: "Ok",
  RequestingForCameraPermissions: "Requesting For Camera Permission",
  NoAccessToCamera: "No access to camera",
  ScannedData: "Scanned Data: ",
  Submit: "Submit",
  Scan: "Scan",
  SoldTickets: "Sold Tickets",
  SomethingWentWrong: "Something went wrong!",
  ReviewQr: "Review QR",
  Edit: "Edit",
  EnterCardNumber: "Enter card number.",
  EnterCardHolderName: "Enter card holder name.",
  EnterCvv: "Enter cvv.",
  EnterExpireMonth: "Enter expire month.",
  EnterExpireYear: "Enter expire year.",
  ExpireMonth: "Expire Month",
  ExpireYear: "Expire Year",
  EnterMobNumber: "Enter your mobile number.",
  Ticket: "Ticket",
  ReviewTicketQR: "Please Review the ticket QR Code",
  ScanQR: "Scan QR",
  ScanTicketQR: "Please Scan ticket QR Code",
  ScanNext: "Scan Next",
  PleaseEnterOtp: "Please enter the otp.",
  ListedTicket : "Listed Ticket"

};
