export default {
  LoginToTicketex: "تسجيل الدخول إلى التذاكر",
  WelcomeAtLogin: "مرحبًا بك في التذكرة ، قم بتسجيل الدخول إلى تطبيقك",
  MobileNo: " (0xxx) رقم الهاتف المحمول",
  Login: "تسجيل الدخول",
  Home: "الصفحة الرئيسية",
  SellTicket: "بيع التذاكر",
  AddTicket: "أضف تذكرة",
  PurchasedTicket: "التذكرة المشتراة",
  Account: "الحساب",
  MyAccount: "حسابي",
  Balance: "توازن",
  BankAccount: "الحساب المصرفي",
  CreditCard: "بطاقة إئتمان",
  ContactUs: "اتصل بنا",
  FAQs: "أسئلة وأجوبة",
  SignOut: "خروج",
  AddNewCreditCard: "إضافة بطاقة ائتمان جديدة",
  AddBankAccount: "إضافة حساب مصرفي",
  YourSellingBalanceIs: "رصيد البيع الخاص بك هو",
  BalancePageBigText:
    "يمكنك استخدام هذا الرصيد لشراء تذكرة أخرى أو يمكنك طلب التحويل إلى حسابك المصرفي",
  WithdrawBalance: "سحب الرصيد",
  BankName: "اسم البنك",
  BeneficiaryName: "أسم المستفيد",
  IBAN: "ذاهبون",
  AddNewBank: "إضافة بنك جديد",
  // CardNumber: "رقم البطاقة",
  // CardHolderName: "إسم صاحب البطاقة",
  Expire: "تنقضي",
  CVV: "ج ب ب",
  PhoneNumber: "رقم الهاتف",
  MessageHere: "رسالة هنا",
  Send: "إرسال",
  TicketDetails: "تفاصيل التذكرة",
  OpenOnMaps: "افتحه على الخرائط",
  OrYouCanScanQRCode: "أو يمكنك مسح رمز الاستجابة السريعة ضوئيًا",
  Sold: "تم البيع",
  Expired: "تنقضي",
  Listed: "مسجل",
  BuyNow: "اشتري الآن",
  OriginalSellingPrices: "أسعار البيع الأصلية",
  Available: "متاح",
  TicketsSold: "تم بيع التذاكر",
  PriceIncludesFees: "السعر يشمل الرسوم",
  AvailableTickets: "التذاكر المتاحة",
  ShowMore: "أظهر المزيد",
  Search: "بحث",
  OTP_Number: "رقم كلمة المرور لمرة واحدة",
  AddTicket: "أضف تذكرة",
  Next: "التالى",
  SelectCategory: "اختر الفئة",
  SelectCity: "اختر مدينة",
  TicketsSold: "تم بيع التذاكر",
  OneTicketFor: "تذكرة واحدة لـ",
  Loading: "جار التحميل",
  EnterYourBankIban: "أدخل رقم الآيبان المصرفي الخاص بك.",
  EnterYourBankBeneficiaryName: "أدخل اسم المستفيد من البنك الخاص بك.",
  EnterYourBankName: "أدخل اسم البنك الخاص بك.",
  SelectEventType: "حدد نوع الحدث",
  SelectClassType: "حدد نوع الفصل",
  Quantity: "كمية",
  PricePerTicket: "سعر التذكرة",
  Note: "بناءً على فئة التذكرة يجب ألا يتجاوز السعر 240 ريال سعودي",
  TicketName: "اسم التذكرة",
  TicketDescription: "وصف التذكرة",
  Next: "التالي",
  Price: "سعر",
  TypeToSearch: "اكتب هنا للبحث...",
  EnterPrice: "أدخل سعر التذكرة.",
  EnterName: "أدخل الاسم.",
  EnterPhoneNo: "أدخل رقم هاتفك.",
  EnterMessage: "أدخل رسالتك",
  Clear: "صاف",
  AreYouSure: "هل أنت متأكد أنك تريد أن تقدم",
  Ok: "حسنا",
  RequestingForCameraPermissions: "طلب إذن الكاميرا",
  NoAccessToCamera: "لا يمكن الوصول إلى الكاميرا",
  ScannedData: "البيانات الممسوحة ضوئيًا ",
  Submit: "سلم",
  Scan: "تصفح",
  SoldTickets: "التذاكر المباعة",
  SomethingWentWrong: "هناك خطأ ما",
  ReviewQr: "رمز الاستجابة السريعة",
  Edit: "تعديل",
  EnterCardNumber: "أدخل رقم البطاقة",
  EnterCardHolderName: "أدخل اسم حامل البطاقة",
  EnterCvv: "أدخل cvv.",
  EnterExpireMonth: "أدخل شهر انتهاء الصلاحية",
  EnterExpireYear: "أدخل سنة انتهاء الصلاحية",
  ExpireMonth: "شهر انتهاء الصلاحية",
  ExpireYear: "سنة انتهاء الصلاحية",
  EnterMobNumber: "أدخل رقم هاتفك المحمول.",
  Ticket: "بطاقة دخول",
  ReviewTicketQR: "يرجى مراجعة رمز الاستجابة السريعة للتذكرة",
  ScanQR: "مسح رمز الاستجابة السريعة",
  ScanTicketQR: "يرجى مسح رمز الاستجابة السريعة للتذكرة ضوئيًا",
  ScanNext: "تفحص التالي",
  PleaseEnterOtp: "الرجاء إدخال الرقم.",
  ListedTicket: "التذكرة المدرجة",
  TicketCreatedSuccessfully: "تم إنشاء التذكرة بنجاح",
  NumberShouldStartWith0: "يجب أن يبدأ الرقم بصفر.",
  QuantityWarn: "لا يمكن أن تتجاوز الكمية ",
  Note: "بناءً على فئة التذكرة ، يجب ألا يتجاوز السعر ",
  Congratulation: "تهنئة!",
  Sorry: "آسف!",
  Success: "Success!",
  Total: "مجموع:",
  Proceed: "تقدم",
  SelectQuantity: "حدد الكمية التي تريد شرائها.",
  PleaseSelectQuantity: "الرجاء تحديد كمية",

  CardHolderName: "اسم حامل البطاقة",
  CardNumber: "رقم البطاقة",
  CardExpiry: "انقضاء",
  CardCvv: "CVV",
  CardFullName: "الاسم بالكامل",

  CardNoIncomplete: "رقم البطاقة غير مكتمل.",
  CardNoNValid: "أدخل رقم بطاقة صالح.",
  CardExpIncomplete: "انتهاء الصلاحية غير مكتمل.",
  CardExpNValid: "أدخل انتهاء صلاحية صالحًا.",
  CardCvvIncomplete: "cvv غير مكتمل",
  CardCvvNValid: "أدخل رمز cvv صالحًا.",
  CardNameIncomplete: "اسم غير مكتمل.",
  CardNameNValid: "أدخل اسمًا صالحًا.",
  CardNValid: "التفاصيل غير صحيحة ، تحقق مرة أخرى!",

  EnterValidIban: "أدخل رقم iban صالحًا.",
  EnterValidBenf: "أدخل اسم مستفيد صالحًا.",
  EnterValidBank: "أدخل اسم بنك صالحًا.",
  Name: "اسم",
  WithdrawBalanceHistory: "سحب تاريخ الرصيد",
  UniqueId: "معرف فريد:",
  AccountId: "معرف الحساب:",
  Address: "عنوان",
  EnterAddress: "أدخل العنوان.",
};
