export default {
  LoginToTicketex: "Login to Ticketex",
  WelcomeAtLogin: "Welcome to Ticketex, login to our app",
  MobileNo: "Mobile number",
  Login: "Login",
  Home: "Home",
  SellTicket: "Sell Ticket",
  PurchasedTicket: "Purchased Ticket",
  Account: "Account",
  MyAccount: "My Account",
  Balance: "Balance",
  BankAccount: "Bank Account",
  CreditCard: "Credit Card",
  ContactUs: "Contact Us",
  FAQs: "FAQs",
  SignOut: "Sign Out",
  AddNewCreditCard: "Add New Credit card",
  AddBankAccount: "Add Bank Account",

  YourSellingBalanceIs: "Your Selling Balance is",
  BalancePageBigText:
    "You can use this balance to buy other ticket or you can request transfer to your bank account",
  WithdrawBalance: "Withdraw Balance",
  BankName: "Bank Name",
  BeneficiaryName: "Beneficiary Name",
  IBAN: "IBAN",
  AddNewBank: "Add New Bank",
  CardNumber: "Card Number",
  CardHolderName: "Card Holder Name",
  Expire: "Expire",
  CVV: "CVV",
  PhoneNumber: "Phone Number",
  MessageHere: "Message Here",
  Send: "Send",
  TicketDetails: "Ticket Details",
  OpenOnGoogleMaps: "Open on google maps",
  OrYouCanScanQRCode: "Or you can scan QR code",
  MyListing: "My Listing",
  Sold: "Sold",
  Expired: "Expired",
  Listed: "Listed",
  BuyNow: "Buy Now",
  OriginalSellingPrices: "Original Selling Prices",
  Available: "Available",
  TicketsSold: "Tickets Sold",
  PriceIncludesFees: "Price includes fees",
  AvailableTickets: "Available Tickets",
  ShowMore: "Show More",
  Search: "Search",

  MyTickets: "My Tickets",
  OTP_Number: "OTP Number",
  ResendOTPNumber: "Resend OTP Number",
  AddTicket: "Add Ticket",
};
